name: Build and Release Flutter App

# This workflow is triggered when a new release is created in GitHub
on:
  push:
    tags:
      - "v*.*.*" # Trigger on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java for the Android build process
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Set up Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.32.4" # Use a specific version for consistency
          cache: true

      # 4. Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # # 5. Run Unit & Widget Tests (as requested)
      # - name: Run tests
      #   run: flutter test

      # 6. Decode and set up the signing key
      - name: Decode Keystore
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
        run: |
          echo $SIGNING_KEY_BASE64 | base64 --decode > android/app/upload-keystore.jks

      # 7. Build the Android App Bundle (AAB)
      - name: Build Android App Bundle
        run: flutter build appbundle --release --build-name=${{ github.ref_name }} --build-number=${{ github.run_number }}
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

      # 8. Upload the AAB to the Google Play Store
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.leapindev.compound_interest_calculator # IMPORTANT: Change this!
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production # Use 'internal', 'alpha', 'beta', or 'production'
          status: completed # Use 'completed' to roll out fully, or 'draft'
